# Generated by Django 5.1.4 on 2024-12-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='register',
            name='country',
        ),
        migrations.RemoveField(
            model_name='register',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='register',
            name='profile_img',
        ),
    ]
